#!/usr/bin/env python3

import argparse
import json
import os
from pathlib import Path
from typing import List

import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

CHARS = " .:-=+*#%@"


def to_ascii(img: np.ndarray) -> List[str]:
    img = np.clip(img, 0.0, 1.0)
    rows = []
    levels = len(CHARS) - 1
    for row in img:
        row_chars = []
        for val in row:
            idx = int(val * levels)
            if idx < 0:
                idx = 0
            elif idx > levels:
                idx = levels
            row_chars.append(CHARS[idx])
        rows.append("".join(row_chars))
    return rows


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser("Visualize denoised vs clean samples from a .npz dataset.")
    parser.add_argument(
        "--input",
        type=str,
        default="/sqfs/work/cm9029/${USER_ID}/gmlp_project/data/denoise/mnist_lambda1.npz",
        help="Noisy dataset generated by build_denoise_datasets.py",
    )
    parser.add_argument("--samples", type=int, default=8, help="Number of samples to display")
    parser.add_argument(
        "--indices",
        type=int,
        nargs="*",
        default=None,
        help="Specific indices to display (overrides --samples)",
    )
    parser.add_argument(
        "--split",
        choices=("train", "test"),
        default="test",
        help="Choose between noisy_test/clean_test or noisy_train/clean_train",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="./denoise_sample_outputs",
        help="Directory to store PNG grids",
    )
    parser.add_argument(
        "--as-json",
        action="store_true",
        help="Print raw arrays as JSON instead of ASCII art",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    npz_path = Path(args.input)
    if not npz_path.exists():
        raise FileNotFoundError(npz_path)
    with np.load(npz_path) as data:
        noisy_key = f"noisy_{args.split}"
        clean_key = f"clean_{args.split}"
        if noisy_key not in data or clean_key not in data:
            raise KeyError(f"{noisy_key}/{clean_key} not found in {npz_path}")
        noisy = data[noisy_key]
        clean = data[clean_key]
        labels = data.get(f"labels_{args.split}")

    num_samples = len(noisy)
    if args.indices:
        idx = np.array([i for i in args.indices if 0 <= i < num_samples], dtype=int)
    else:
        rng = np.random.default_rng(0)
        idx = rng.permutation(num_samples)[: args.samples]
        idx.sort()

    print(json.dumps({"input": str(npz_path), "split": args.split, "indices": idx.tolist()}, ensure_ascii=False))
    saved_clean = []
    saved_noisy = []
    saved_labels = []
    for i in idx:
        c = clean[i, 0]
        n = noisy[i, 0]
        label = int(labels[i]) if labels is not None else None
        meta = {
            "index": int(i),
            "label": label,
            "clean_min": float(c.min()),
            "clean_max": float(c.max()),
            "noisy_min": float(n.min()),
            "noisy_max": float(n.max()),
        }
        if args.as_json:
            meta["clean"] = c.tolist()
            meta["noisy"] = n.tolist()
            print(json.dumps(meta, ensure_ascii=False))
        else:
            print(json.dumps(meta, ensure_ascii=False))
            clean_ascii = to_ascii(c)
            noisy_ascii = to_ascii(n)
            for row_c, row_n in zip(clean_ascii, noisy_ascii):
                print(f"{row_c}  |  {row_n}")
            print("-" * 64)
        saved_clean.append(c)
        saved_noisy.append(n)
        saved_labels.append(label)

    if args.output_dir:
        out_dir = Path(args.output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / f"{npz_path.stem}_{args.split}_{len(idx)}samples.png"
        save_png(saved_clean, saved_noisy, saved_labels, idx.tolist(), out_path)
        print(f"[png] saved {out_path}")
    return 0


def save_png(clean_list, noisy_list, label_list, indices, out_path: Path):
    if not clean_list:
        return
    rows = len(clean_list)
    fig, axes = plt.subplots(rows, 2, figsize=(4, 2 * rows))
    axes = np.atleast_2d(axes)
    for r, (ax_clean, ax_noisy) in enumerate(axes):
        c = clean_list[r]
        n = noisy_list[r]
        label = label_list[r]
        idx = indices[r]
        ax_clean.imshow(c, cmap="gray", vmin=0.0, vmax=1.0)
        ax_clean.set_title(f"clean #{idx}" + (f" (y={label})" if label is not None else ""))
        ax_clean.axis("off")
        ax_noisy.imshow(n, cmap="gray", vmin=0.0, vmax=1.0)
        ax_noisy.set_title("noisy")
        ax_noisy.axis("off")
    fig.tight_layout()
    fig.savefig(out_path, dpi=200)
    plt.close(fig)


if __name__ == "__main__":
    raise SystemExit(main())
